name: Read File Lines

on: 
  workflow_dispatch

jobs:
  read_lines_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        # The checkout action is needed to access files in your repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PBI_TOKEN }}

      - name: Read and echo each line
        run: |
          FILE2=src/names.txt
          # Use a while loop with 'read -r' for robust line reading
          while read -r line; do
            echo "Processing line: $line"
          done < "$FILE2"
        # Specify bash shell if needed (default on ubuntu-latest)
        shell: bash

      - name: Delete Revision4 branch if exists
        run: |
          if git ls-remote --heads origin Revision4 | grep -q Revision4; then
            echo "Branch Revision4 exists, deleting..."
            git push origin --delete Revision4
          else
            echo "Branch Revision4 does not exist"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PBI_TOKEN }}

      - name: Create PR to remove folders
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b Revision4
          FILE2=src/names.txt
          while read -r line; do
            echo "Processing line: XXX/$line"
            rm -rf "XXX/$line"
          done < "$FILE2"

          git add -A
          git commit -m "Remove folder1 and folder2"
          git push -u origin Revision4
        env:
          GITHUB_TOKEN: ${{ secrets.PBI_TOKEN }}

      - name: Create Pull Request
        run: |
          gh pr create --base main --head Revision4 --title "Remove folder1 and folder2" --body "This PR removes folder1 and folder2 from the repository."
        env:
          GITHUB_TOKEN: ${{ secrets.PBI_TOKEN }}
